FROM registry.cn-zhangjiakou.aliyuncs.com/linux-practice/base-image:latest
COPY func.sh /etc/profile.d
RUN cd /opt/software && \
    curl -LO https://dlcdn.apache.org/zookeeper/zookeeper-3.7.1/apache-zookeeper-3.7.1-bin.tar.gz

