name: Extract Tar
on:
  workflow_dispatch:
  push:
    paths:
      - extract-tar/**
  workflow_run:
    workflows: [Base Image]
    types: [completed]

env:
  REGISTRY: registry.cn-zhangjiakou.aliyuncs.com
  NAMESPACE: linux-practice
  IMAGE: extract-tar

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          TAG=${{ github.ref_name }}
          docker login \
            --username=${{ secrets.DOCKER_USERNAME }} \
            --password=${{ secrets.DOCKER_PASSWORD }} \
            ${REGISTRY}
          cd extract-tar
          docker build . --file Dockerfile \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG} \
            --tag ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
          docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:latest